In [1]:
import pandas as pd

In [2]:
pd.read_csv("pokemon.csv")

        Pokemon      Type
0     Bulbasaur     Grass
1       Ivysaur     Grass
2      Venusaur     Grass
3    Charmander      Fire
4    Charmeleon      Fire
5     Charizard      Fire
6      Squirtle     Water
7     Wartortle     Water
8     Blastoise     Water
9      Caterpie       Bug
10      Metapod       Bug
11   Butterfree       Bug
12       Weedle       Bug
13       Kakuna       Bug
14     Beedrill       Bug
15       Pidgey    Normal
16    Pidgeotto    Normal
17      Pidgeot    Normal
18      Rattata    Normal
19     Raticate    Normal
20      Spearow    Normal
21       Fearow    Normal
22        Ekans    Poison
23        Arbok    Poison
24      Pikachu  Electric
25       Raichu  Electric
26    Sandshrew    Ground
27    Sandslash    Ground
28      Nidoran    Poison
29     Nidorina    Poison
..          ...       ...
691   Clauncher     Water
692   Clawitzer     Water
693  Helioptile  Electric
694   Heliolisk  Electric
695      Tyrunt      Rock
696   Tyrantrum      Rock
697      Amaura      Rock
698     Aurorus      Rock
699     Sylveon     Fairy
700    Hawlucha  Fighting
701     Dedenne  Electric
702     Carbink      Rock
703       Goomy    Dragon
704     Sliggoo    Dragon
705      Goodra    Dragon
706      Klefki     Steel
707    Phantump     Ghost
708   Trevenant     Ghost
709   Pumpkaboo     Ghost
710   Gourgeist     Ghost
711    Bergmite       Ice
712     Avalugg       Ice
713      Noibat    Flying
714     Noivern    Flying
715     Xerneas     Fairy
716     Yveltal      Dark
717     Zygarde    Dragon
718     Diancie      Rock
719       Hoopa   Psychic
720   Volcanion      Fire

[721 rows x 2 columns]

In [3]:
pd.read_csv("pokemon.csv",usecols=["Pokemon"],squeeze=False)

        Pokemon
0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
5     Charizard
6      Squirtle
7     Wartortle
8     Blastoise
9      Caterpie
10      Metapod
11   Butterfree
12       Weedle
13       Kakuna
14     Beedrill
15       Pidgey
16    Pidgeotto
17      Pidgeot
18      Rattata
19     Raticate
20      Spearow
21       Fearow
22        Ekans
23        Arbok
24      Pikachu
25       Raichu
26    Sandshrew
27    Sandslash
28      Nidoran
29     Nidorina
..          ...
691   Clauncher
692   Clawitzer
693  Helioptile
694   Heliolisk
695      Tyrunt
696   Tyrantrum
697      Amaura
698     Aurorus
699     Sylveon
700    Hawlucha
701     Dedenne
702     Carbink
703       Goomy
704     Sliggoo
705      Goodra
706      Klefki
707    Phantump
708   Trevenant
709   Pumpkaboo
710   Gourgeist
711    Bergmite
712     Avalugg
713      Noibat
714     Noivern
715     Xerneas
716     Yveltal
717     Zygarde
718     Diancie
719       Hoopa
720   Volcanion

[721 rows x 1 columns]

In [4]:
pd.read_csv("google_stock_price.csv",squeeze=False)

      Stock Price
0           50.12
1           54.10
2           54.65
3           52.38
4           52.95
5           53.90
6           53.02
7           50.95
8           51.13
9           50.07
10          50.70
11          49.95
12          50.74
13          51.10
14          51.10
15          52.61
16          53.70
17          55.69
18          55.94
19          56.93
20          58.69
21          59.62
22          58.86
23          59.13
24          60.35
25          59.86
26          59.07
27          63.37
28          65.47
29          64.74
...           ...
2982       675.22
2983       668.26
2984       680.04
2985       684.11
2986       692.10
2987       699.21
2988       694.49
2989       697.77
2990       695.36
2991       705.63
2992       715.09
2993       720.64
2994       716.98
2995       720.95
2996       719.85
2997       733.78
2998       736.96
2999       741.19
3000       738.63
3001       742.74
3002       739.77
3003       738.42
3004       741.77
3005       745.91
3006       768.79
3007       772.88
3008       771.07
3009       773.18
3010       771.61
3011       782.22

[3012 rows x 1 columns]

In [5]:
pokemon=pd.read_csv("pokemon.csv",squeeze=False)

In [6]:
pokemon.head(5)

      Pokemon   Type
0   Bulbasaur  Grass
1     Ivysaur  Grass
2    Venusaur  Grass
3  Charmander   Fire
4  Charmeleon   Fire

In [7]:
pokemon.tail(4)

       Pokemon     Type
717    Zygarde   Dragon
718    Diancie     Rock
719      Hoopa  Psychic
720  Volcanion     Fire

In [8]:
len(pokemon)

721

In [9]:
type(pokemon)

pandas.core.frame.DataFrame

In [10]:
pd.read_csv("pokemon.csv")

        Pokemon      Type
0     Bulbasaur     Grass
1       Ivysaur     Grass
2      Venusaur     Grass
3    Charmander      Fire
4    Charmeleon      Fire
5     Charizard      Fire
6      Squirtle     Water
7     Wartortle     Water
8     Blastoise     Water
9      Caterpie       Bug
10      Metapod       Bug
11   Butterfree       Bug
12       Weedle       Bug
13       Kakuna       Bug
14     Beedrill       Bug
15       Pidgey    Normal
16    Pidgeotto    Normal
17      Pidgeot    Normal
18      Rattata    Normal
19     Raticate    Normal
20      Spearow    Normal
21       Fearow    Normal
22        Ekans    Poison
23        Arbok    Poison
24      Pikachu  Electric
25       Raichu  Electric
26    Sandshrew    Ground
27    Sandslash    Ground
28      Nidoran    Poison
29     Nidorina    Poison
..          ...       ...
691   Clauncher     Water
692   Clawitzer     Water
693  Helioptile  Electric
694   Heliolisk  Electric
695      Tyrunt      Rock
696   Tyrantrum      Rock
697      Amaura      Rock
698     Aurorus      Rock
699     Sylveon     Fairy
700    Hawlucha  Fighting
701     Dedenne  Electric
702     Carbink      Rock
703       Goomy    Dragon
704     Sliggoo    Dragon
705      Goodra    Dragon
706      Klefki     Steel
707    Phantump     Ghost
708   Trevenant     Ghost
709   Pumpkaboo     Ghost
710   Gourgeist     Ghost
711    Bergmite       Ice
712     Avalugg       Ice
713      Noibat    Flying
714     Noivern    Flying
715     Xerneas     Fairy
716     Yveltal      Dark
717     Zygarde    Dragon
718     Diancie      Rock
719       Hoopa   Psychic
720   Volcanion      Fire

[721 rows x 2 columns]

In [11]:
pd.read_csv("google_stock_price.csv",squeeze=False)

      Stock Price
0           50.12
1           54.10
2           54.65
3           52.38
4           52.95
5           53.90
6           53.02
7           50.95
8           51.13
9           50.07
10          50.70
11          49.95
12          50.74
13          51.10
14          51.10
15          52.61
16          53.70
17          55.69
18          55.94
19          56.93
20          58.69
21          59.62
22          58.86
23          59.13
24          60.35
25          59.86
26          59.07
27          63.37
28          65.47
29          64.74
...           ...
2982       675.22
2983       668.26
2984       680.04
2985       684.11
2986       692.10
2987       699.21
2988       694.49
2989       697.77
2990       695.36
2991       705.63
2992       715.09
2993       720.64
2994       716.98
2995       720.95
2996       719.85
2997       733.78
2998       736.96
2999       741.19
3000       738.63
3001       742.74
3002       739.77
3003       738.42
3004       741.77
3005       745.91
3006       768.79
3007       772.88
3008       771.07
3009       773.18
3010       771.61
3011       782.22

[3012 rows x 1 columns]

In [12]:
pd.read_csv("google_stock_price.csv",squeeze=False)

      Stock Price
0           50.12
1           54.10
2           54.65
3           52.38
4           52.95
5           53.90
6           53.02
7           50.95
8           51.13
9           50.07
10          50.70
11          49.95
12          50.74
13          51.10
14          51.10
15          52.61
16          53.70
17          55.69
18          55.94
19          56.93
20          58.69
21          59.62
22          58.86
23          59.13
24          60.35
25          59.86
26          59.07
27          63.37
28          65.47
29          64.74
...           ...
2982       675.22
2983       668.26
2984       680.04
2985       684.11
2986       692.10
2987       699.21
2988       694.49
2989       697.77
2990       695.36
2991       705.63
2992       715.09
2993       720.64
2994       716.98
2995       720.95
2996       719.85
2997       733.78
2998       736.96
2999       741.19
3000       738.63
3001       742.74
3002       739.77
3003       738.42
3004       741.77
3005       745.91
3006       768.79
3007       772.88
3008       771.07
3009       773.18
3010       771.61
3011       782.22

[3012 rows x 1 columns]

In [13]:
google=pd.read_csv("google_stock_price.csv",squeeze=False)

In [14]:
type(google)

pandas.core.frame.DataFrame

In [15]:
sorted(google)

['Stock Price']

In [16]:
sorted(pokemon["Pokemon"])

['Abomasnow',
 'Abra',
 'Absol',
 'Accelgor',
 'Aegislash',
 'Aerodactyl',
 'Aggron',
 'Aipom',
 'Alakazam',
 'Alomomola',
 'Altaria',
 'Amaura',
 'Ambipom',
 'Amoonguss',
 'Ampharos',
 'Anorith',
 'Arbok',
 'Arcanine',
 'Arceus',
 'Archen',
 'Archeops',
 'Ariados',
 'Armaldo',
 'Aromatisse',
 'Aron',
 'Articuno',
 'Audino',
 'Aurorus',
 'Avalugg',
 'Axew',
 'Azelf',
 'Azumarill',
 'Azurill',
 'Bagon',
 'Baltoy',
 'Banette',
 'Barbaracle',
 'Barboach',
 'Basculin',
 'Bastiodon',
 'Bayleef',
 'Beartic',
 'Beautifly',
 'Beedrill',
 'Beheeyem',
 'Beldum',
 'Bellossom',
 'Bellsprout',
 'Bergmite',
 'Bibarel',
 'Bidoof',
 'Binacle',
 'Bisharp',
 'Blastoise',
 'Blaziken',
 'Blissey',
 'Blitzle',
 'Boldore',
 'Bonsly',
 'Bouffalant',
 'Braixen',
 'Braviary',
 'Breloom',
 'Bronzong',
 'Bronzor',
 'Budew',
 'Buizel',
 'Bulbasaur',
 'Buneary',
 'Bunnelby',
 'Burmy',
 'Butterfree',
 'Cacnea',
 'Cacturne',
 'Camerupt',
 'Carbink',
 'Carnivine',
 'Carracosta',
 'Carvanha',
 'Cascoon',
 'Castform',
 'Caterpie',
 'Celebi',
 'Chandelure',
 'Chansey',
 'Charizard',
 'Charmander',
 'Charmeleon',
 'Chatot',
 'Cherrim',
 'Cherubi',
 'Chesnaught',
 'Chespin',
 'Chikorita',
 'Chimchar',
 'Chimecho',
 'Chinchou',
 'Chingling',
 'Cinccino',
 'Clamperl',
 'Clauncher',
 'Clawitzer',
 'Claydol',
 'Clefable',
 'Clefairy',
 'Cleffa',
 'Cloyster',
 'Cobalion',
 'Cofagrigus',
 'Combee',
 'Combusken',
 'Conkeldurr',
 'Corphish',
 'Corsola',
 'Cottonee',
 'Cradily',
 'Cranidos',
 'Crawdaunt',
 'Cresselia',
 'Croagunk',
 'Crobat',
 'Croconaw',
 'Crustle',
 'Cryogonal',
 'Cubchoo',
 'Cubone',
 'Cyndaquil',
 'Darkrai',
 'Darmanitan',
 'Darumaka',
 'Dedenne',
 'Deerling',
 'Deino',
 'Delcatty',
 'Delibird',
 'Delphox',
 'Deoxys',
 'Dewgong',
 'Dewott',
 'Dialga',
 'Diancie',
 'Diggersby',
 'Diglett',
 'Ditto',
 'Dodrio',
 'Doduo',
 'Donphan',
 'Doublade',
 'Dragalge',
 'Dragonair',
 'Dragonite',
 'Drapion',
 'Dratini',
 'Drifblim',
 'Drifloon',
 'Drilbur',
 'Drowzee',
 'Druddigon',
 'Ducklett',
 'Dugtrio',
 'Dunsparce',
 'Duosion',
 'Durant',
 'Dusclops',
 'Dusknoir',
 'Duskull',
 'Dustox',
 'Dwebble',
 'Eelektrik',
 'Eelektross',
 'Eevee',
 'Ekans',
 'Electabuzz',
 'Electivire',
 'Electrike',
 'Electrode',
 'Elekid',
 'Elgyem',
 'Emboar',
 'Emolga',
 'Empoleon',
 'Entei',
 'Escavalier',
 'Espeon',
 'Espurr',
 'Excadrill',
 'Exeggcute',
 'Exeggutor',
 'Exploud',
 "Farfetch'd",
 'Fearow',
 'Feebas',
 'Fennekin',
 'Feraligatr',
 'Ferroseed',
 'Ferrothorn',
 'Finneon',
 'Flaaffy',
 'FlabÃ©bÃ©',
 'Flareon',
 'Fletchinder',
 'Fletchling',
 'Floatzel',
 'Floette',
 'Florges',
 'Flygon',
 'Foongus',
 'Forretress',
 'Fraxure',
 'Frillish',
 'Froakie',
 'Frogadier',
 'Froslass',
 'Furfrou',
 'Furret',
 'Gabite',
 'Gallade',
 'Galvantula',
 'Garbodor',
 'Garchomp',
 'Gardevoir',
 'Gastly',
 'Gastrodon',
 'Genesect',
 'Gengar',
 'Geodude',
 'Gible',
 'Gigalith',
 'Girafarig',
 'Giratina',
 'Glaceon',
 'Glalie',
 'Glameow',
 'Gligar',
 'Gliscor',
 'Gloom',
 'Gogoat',
 'Golbat',
 'Goldeen',
 'Golduck',
 'Golem',
 'Golett',
 'Golurk',
 'Goodra',
 'Goomy',
 'Gorebyss',
 'Gothita',
 'Gothitelle',
 'Gothorita',
 'Gourgeist',
 'Granbull',
 'Graveler',
 'Greninja',
 'Grimer',
 'Grotle',
 'Groudon',
 'Grovyle',
 'Growlithe',
 'Grumpig',
 'Gulpin',
 'Gurdurr',
 'Gyarados',
 'Happiny',
 'Hariyama',
 'Haunter',
 'Hawlucha',
 'Haxorus',
 'Heatmor',
 'Heatran',
 'Heliolisk',
 'Helioptile',
 'Heracross',
 'Herdier',
 'Hippopotas',
 'Hippowdon',
 'Hitmonchan',
 'Hitmonlee',
 'Hitmontop',
 'Ho-oh',
 'Honchkrow',
 'Honedge',
 'Hoopa',
 'Hoothoot',
 'Hoppip',
 'Horsea',
 'Houndoom',
 'Houndour',
 'Huntail',
 'Hydreigon',
 'Hypno',
 'Igglybuff',
 'Illumise',
 'Infernape',
 'Inkay',
 'Ivysaur',
 'Jellicent',
 'Jigglypuff',
 'Jirachi',
 'Jolteon',
 'Joltik',
 'Jumpluff',
 'Jynx',
 'Kabuto',
 'Kabutops',
 'Kadabra',
 'Kakuna',
 'Kangaskhan',
 'Karrablast',
 'Kecleon',
 'Keldeo',
 'Kingdra',
 'Kingler',
 'Kirlia',
 'Klang',
 'Klefki',
 'Klink',
 'Klinklang',
 'Koffing',
 'Krabby',
 'Kricketot',
 'Kricketune',
 'Krokorok',
 'Krookodile',
 'Kyogre',
 'Kyurem',
 'Lairon',
 'Lampent',
 'Landorus',
 'Lanturn',
 'Lapras',
 'Larvesta',
 'Larvitar',
 'Latias',
 'Latios',
 'Leafeon',
 'Leavanny',
 'Ledian',
 'Ledyba',
 'Lickilicky',
 'Lickitung',
 'Liepard',
 'Lileep',
 'Lilligant',
 'Lillipup',
 'Linoone',
 'Litleo',
 'Litwick',
 'Lombre',
 'Lopunny',
 'Lotad',
 'Loudred',
 'Lucario',
 'Ludicolo',
 'Lugia',
 'Lumineon',
 'Lunatone',
 'Luvdisc',
 'Luxio',
 'Luxray',
 'Machamp',
 'Machoke',
 'Machop',
 'Magby',
 'Magcargo',
 'Magikarp',
 'Magmar',
 'Magmortar',
 'Magnemite',
 'Magneton',
 'Magnezone',
 'Makuhita',
 'Malamar',
 'Mamoswine',
 'Manaphy',
 'Mandibuzz',
 'Manectric',
 'Mankey',
 'Mantine',
 'Mantyke',
 'Maractus',
 'Mareep',
 'Marill',
 'Marowak',
 'Marshtomp',
 'Masquerain',
 'Mawile',
 'Medicham',
 'Meditite',
 'Meganium',
 'Meloetta',
 'Meowstic',
 'Meowth',
 'Mesprit',
 'Metagross',
 'Metang',
 'Metapod',
 'Mew',
 'Mewtwo',
 'Mienfoo',
 'Mienshao',
 'Mightyena',
 'Milotic',
 'Miltank',
 'Mime Jr.',
 'Minccino',
 'Minun',
 'Misdreavus',
 'Mismagius',
 'Moltres',
 'Monferno',
 'Mothim',
 'Mr. Mime',
 'Mudkip',
 'Muk',
 'Munchlax',
 'Munna',
 'Murkrow',
 'Musharna',
 'Natu',
 'Nidoking',
 'Nidoqueen',
 'Nidoran',
 'Nidoranâ™‚',
 'Nidorina',
 'Nidorino',
 'Nincada',
 'Ninetales',
 'Ninjask',
 'Noctowl',
 'Noibat',
 'Noivern',
 'Nosepass',
 'Numel',
 'Nuzleaf',
 'Octillery',
 'Oddish',
 'Omanyte',
 'Omastar',
 'Onix',
 'Oshawott',
 'Pachirisu',
 'Palkia',
 'Palpitoad',
 'Pancham',
 'Pangoro',
 'Panpour',
 'Pansage',
 'Pansear',
 'Paras',
 'Parasect',
 'Patrat',
 'Pawniard',
 'Pelipper',
 'Persian',
 'Petilil',
 'Phanpy',
 'Phantump',
 'Phione',
 'Pichu',
 'Pidgeot',
 'Pidgeotto',
 'Pidgey',
 'Pidove',
 'Pignite',
 'Pikachu',
 'Piloswine',
 'Pineco',
 'Pinsir',
 'Piplup',
 'Plusle',
 'Politoed',
 'Poliwag',
 'Poliwhirl',
 'Poliwrath',
 'Ponyta',
 'Poochyena',
 'Porygon',
 'Porygon-Z',
 'Porygon2',
 'Primeape',
 'Prinplup',
 'Probopass',
 'Psyduck',
 'Pumpkaboo',
 'Pupitar',
 'Purrloin',
 'Purugly',
 'Pyroar',
 'Quagsire',
 'Quilava',
 'Quilladin',
 'Qwilfish',
 'Raichu',
 'Raikou',
 'Ralts',
 'Rampardos',
 'Rapidash',
 'Raticate',
 'Rattata',
 'Rayquaza',
 'Regice',
 'Regigigas',
 'Regirock',
 'Registeel',
 'Relicanth',
 'Remoraid',
 'Reshiram',
 'Reuniclus',
 'Rhydon',
 'Rhyhorn',
 'Rhyperior',
 'Riolu',
 'Roggenrola',
 'Roselia',
 'Roserade',
 'Rotom',
 'Rufflet',
 'Sableye',
 'Salamence',
 'Samurott',
 'Sandile',
 'Sandshrew',
 'Sandslash',
 'Sawk',
 'Sawsbuck',
 'Scatterbug',
 'Sceptile',
 'Scizor',
 'Scolipede',
 'Scrafty',
 'Scraggy',
 'Scyther',
 'Seadra',
 'Seaking',
 'Sealeo',
 'Seedot',
 'Seel',
 'Seismitoad',
 'Sentret',
 'Serperior',
 'Servine',
 'Seviper',
 'Sewaddle',
 'Sharpedo',
 'Shaymin',
 'Shedinja',
 'Shelgon',
 'Shellder',
 'Shellos',
 'Shelmet',
 'Shieldon',
 'Shiftry',
 'Shinx',
 'Shroomish',
 'Shuckle',
 'Shuppet',
 'Sigilyph',
 'Silcoon',
 'Simipour',
 'Simisage',
 'Simisear',
 'Skarmory',
 'Skiddo',
 'Skiploom',
 'Skitty',
 'Skorupi',
 'Skrelp',
 'Skuntank',
 'Slaking',
 'Slakoth',
 'Sliggoo',
 'Slowbro',
 'Slowking',
 'Slowpoke',
 'Slugma',
 'Slurpuff',
 'Smeargle',
 'Smoochum',
 'Sneasel',
 'Snivy',
 'Snorlax',
 'Snorunt',
 'Snover',
 'Snubbull',
 'Solosis',
 'Solrock',
 'Spearow',
 'Spewpa',
 'Spheal',
 'Spinarak',
 'Spinda',
 'Spiritomb',
 'Spoink',
 'Spritzee',
 'Squirtle',
 'Stantler',
 'Staraptor',
 'Staravia',
 'Starly',
 'Starmie',
 'Staryu',
 'Steelix',
 'Stoutland',
 'Stunfisk',
 'Stunky',
 'Sudowoodo',
 'Suicune',
 'Sunflora',
 'Sunkern',
 'Surskit',
 'Swablu',
 'Swadloon',
 'Swalot',
 'Swampert',
 'Swanna',
 'Swellow',
 'Swinub',
 'Swirlix',
 'Swoobat',
 'Sylveon',
 'Taillow',
 'Talonflame',
 'Tangela',
 'Tangrowth',
 'Tauros',
 'Teddiursa',
 'Tentacool',
 'Tentacruel',
 'Tepig',
 'Terrakion',
 'Throh',
 'Thundurus',
 'Timburr',
 'Tirtouga',
 'Togekiss',
 'Togepi',
 'Togetic',
 'Torchic',
 'Torkoal',
 'Tornadus',
 'Torterra',
 'Totodile',
 'Toxicroak',
 'Tranquill',
 'Trapinch',
 'Treecko',
 'Trevenant',
 'Tropius',
 'Trubbish',
 'Turtwig',
 'Tympole',
 'Tynamo',
 'Typhlosion',
 'Tyranitar',
 'Tyrantrum',
 'Tyrogue',
 'Tyrunt',
 'Umbreon',
 'Unfezant',
 'Unown',
 'Ursaring',
 'Uxie',
 'Vanillish',
 'Vanillite',
 'Vanilluxe',
 'Vaporeon',
 'Venipede',
 'Venomoth',
 'Venonat',
 'Venusaur',
 'Vespiquen',
 'Vibrava',
 'Victini',
 'Victreebel',
 'Vigoroth',
 'Vileplume',
 'Virizion',
 'Vivillon',
 'Volbeat',
 'Volcanion',
 'Volcarona',
 'Voltorb',
 'Vullaby',
 'Vulpix',
 'Wailmer',
 'Wailord',
 'Walrein',
 'Wartortle',
 'Watchog',
 'Weavile',
 'Weedle',
 'Weepinbell',
 'Weezing',
 'Whimsicott',
 'Whirlipede',
 'Whiscash',
 'Whismur',
 'Wigglytuff',
 'Wingull',
 'Wobbuffet',
 'Woobat',
 'Wooper',
 'Wormadam',
 'Wurmple',
 'Wynaut',
 'Xatu',
 'Xerneas',
 'Yamask',
 'Yanma',
 'Yanmega',
 'Yveltal',
 'Zangoose',
 'Zapdos',
 'Zebstrika',
 'Zekrom',
 'Zigzagoon',
 'Zoroark',
 'Zorua',
 'Zubat',
 'Zweilous',
 'Zygarde']

In [17]:
pokemon=pd.read_csv("pokemon.csv")

In [18]:
list(google)

['Stock Price']

In [19]:
list(pokemon)

['Pokemon', 'Type']

In [20]:
pokemon.shape

(721, 2)

In [21]:
google.ndim

2

In [22]:
pokemon.ndim

2

In [23]:
google.index

RangeIndex(start=0, stop=3012, step=1)

In [24]:
google.values

array([[ 50.12],
       [ 54.1 ],
       [ 54.65],
       ...,
       [773.18],
       [771.61],
       [782.22]])

In [2]:
Pokemon(value)

NameError: name 'Pokemon' is not defined

In [26]:
pokemon["Pokemon"].is_unique

True

In [27]:
pokemon["Type"].is_unique

False

In [47]:
100 in pokemon

False

In [30]:
100 in pokemon.index

True

In [38]:
"picakhu" in pokemon

False

In [63]:
pokemon =pd.read_csv("pokemon.csv",usecols=["Pokemon"],squeeze=True)

In [64]:
100 in pokemon

True